TaskarCenterAtUW/TDEI-api-tester

- src/__tests__/general.test.ts
- src/__tests__/osw.test.ts
- src/utils.ts
Minor refactoring and changed the test patterns for better readability
Given
When
Then
> Minor refactoring and changed the test patterns to for better readability

- src/__tests__/general.test.ts
- src/__tests__/gtfsflex.test.ts
- src/__tests__/gtfspathways.test.ts
Test cases for below mentioned APIs. Also attached are the test results for the same.
GeneralAPI:
- listOrganizations
- listStations
- listApiVersions [Failing due to inconsistent schema]
- getStatus (in progress)
GTFSFlexAPI
- listFlexServices
- listFlexVersions
- listFlexFiles
GTFSPathwaysAPI
- listPathwaysFiles
- listStations
- listPathwaysVersions
Environment: STAGE
Note: Failed test cases are because of insufficient input data.
> Test Cases 

- src/__tests__/gtfspathways.test.ts
- src/utils.ts
Test case for uploadPathwaysFileForm in GTFS Pathways.
> test case for GTFS pathways file upload

- .gitignore
- README.md
- jest.config.ts
- src/__tests__/general.test.ts
- src/__tests__/gtfsflex.test.ts
- src/__tests__/gtfspathways.test.ts
- src/__tests__/osw.test.ts
- src/index.ts
- src/utils.ts
- Consider Adding tests in the below format
> Given
- Setup test data in this step
- Give a line break
> When
- Perform some action
- Give a line break
> Then
- Assert result
``` js 
describe('my-awesome-test', () => {
const getTestData => return {};
it('should validate schema response', () => {
let testData = getTestData();
let api = new myAwesomeApi();
const result = api.getVersions();
expect(result.status).toBe(200);
expect(result.myAwesomeField).toBe('valid');
});
});
```
> Adding instructions and cleanup existing test files

- package.json
- src/models/types.ts
- src/seeder.ts
- src/utils.ts
**What this PR does ?**
- Create an organization with random org data
- Create a flex service
- Create a pathways station
- Create  4 random users with below - 
- Role **poc**
- Role **flex_data_generator**
- Role **pathways_data_generator**
- Role **osw_data_generator**
- Activate Organisation
- De-activate Organisation
**How to use this ?**
```
import {Seeder} from './seeder'
const run = async () => {
const seeder = new Seeder()
const seedData = await seeder.seed() 
// this will return the seed data
/*
{
"tdei_org_id":"4fd7c367-d7c3-49c3-9c7e-8e8ec6056169",
"service_id":"fc7afae7-b406-4b36-af83-621aab026d8c",
"station_id":"4aeb1717-c651-4d27-8ee5-34fdcf199bfa",
"users":{
"poc":{
"username":"susan3@gmail.com",
"password":"Pa$s1word"
},
"flex_data_generator":{ …
```
> Added Seeder for testing

- README.md
- package.json
- src/models/types.ts
- src/seeder.ts
- src/utils.ts
Added Seeder - 
**What this PR does ?**
- Create an organization with random org data
- Create a flex service
- Create a pathways station
- Create  4 random users with below - 
- Role **poc**
- Role **flex_data_generator**
- Role **pathways_data_generator**
- Role **osw_data_generator**
- Activate Organisation
- De-activate Organisation
**How to use this ?**
```
import {Seeder} from './seeder'
const run = async () => {
const seeder = new Seeder()
const seedData = await seeder.seed() 
// this will return the seed data
/*
{
"tdei_org_id":"4fd7c367-d7c3-49c3-9c7e-8e8ec6056169",
"service_id":"fc7afae7-b406-4b36-af83-621aab026d8c",
"station_id":"4aeb1717-c651-4d27-8ee5-34fdcf199bfa",
"users":{
"poc":{
"username":"susan3@gmail.com",
"password":"Pa$s1word"
},
"flex_data_generator":{ …
```
> Feature seeder requirements

- package-lock.json
- src/__tests__/general.test.ts
- Refactored general tests to reflect similar to the ones at user-management-api-test
> General tests refactored

- src/__tests__/gtfsflex.test.ts
- src/seeder.ts
- src/utils.ts
- Flex is refactored with new data
- Seeder used in some cases (for upload)
Reference Task : [Task 322](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/322): Flex API tests
> Feature flex refactor

- assets/postman/TDEI-metadata-validation.postman_collection.json
- assets/postman/how-to-test.md
> Testing collection updated

- package.json
- src/environment/environment.ts
- src/seeder.ts
- src/utils.ts
- Replaced test-harness.json with environment functionality. 
Note: 
Create .env file in the root folder of the project and add the required key values to it.
> .env functionality

- package-lock.json
- package.json
- src/__tests__/gtfsflex.test.ts
- src/__tests__/gtfspathways.test.ts
- src/__tests__/osw.test.ts
- src/utils.ts
- wrtitten test cases for OSW file
- Ommited upload and download tests for timebeing to modify axios interceptor for the updated client.
> OSW Test cases

- assets/payloads/osw/files/changeset.txt
- assets/payloads/osw/files/metadata.json
- package-lock.json
- package.json
- src/__tests__/gtfsflex.test.ts
- src/__tests__/gtfspathways.test.ts
- src/__tests__/osw.test.ts
- src/utils.ts
Updated test cases to pass along with the new apis
- upload working for OSW
> updated test cases

- .github/workflows/run_tests.yml
- package-lock.json
- package.json
- src/__tests__/osw.test.ts
- src/utils.ts
API enhancement for invalid metadata changes
> api enhancement for metadata filters

- jest.config.ts
- package-lock.json
- package.json
- src/__tests__/osw.test.ts
backend service api tester coverage
[POST] osw/dataset-flattern
[GET] osw/dataset-flattern/status
[POST] osw/dataset-bbox
[GET] osw/dataset-bbox/status
[GET] osw/dataset-bbox/download
> backend service api tester coverage

- .github/workflows/run_tests.yml
- .gitignore
- assets/payloads/metadata.json
- jest.config.ts
- package-lock.json
- package.json
- scrape.js
- src/__tests__/general.test.ts
- src/__tests__/gtfsflex.test.ts
- src/__tests__/gtfspathways.test.ts
- src/__tests__/osw.test.ts
- src/seeder.ts
- src/utils.ts
1. Updated the test descriptions
2. Replaced reporting library to have better reporting
> Description update and library

- package-lock.json
- package.json
- src/__tests__/general.test.ts
- src/__tests__/gtfsflex.test.ts
- src/__tests__/gtfspathways.test.ts
- src/__tests__/osw.test.ts
Task:
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/994/
- Cloning Dataset api test coverage
- Refactoring
- Persona coverage
> api tester clone dataset

- package-lock.json
- package.json
- src/__tests__/general.test.ts
- src/__tests__/gtfsflex.test.ts
- src/__tests__/gtfspathways.test.ts
- src/__tests__/osw.test.ts
- src/seeder.ts
- Includes test for job progress 
- Includes issue fix for cloning dataset
- Reference task [Task 990](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/990): Feature 3.1 – Improve messaging from job status, especially for long-running jobs.
- Unit tests run locally
> Feature 990

- package-lock.json
- package.json
- src/__tests__/gtfsflex.test.ts
- src/__tests__/gtfspathways.test.ts
- src/__tests__/osw.test.ts
- Added test cases for quality metric
- Enhanced tests for Job status and its progress
> Feature 993

- assets/payloads/osw/tag-quality.json
- jest.config.ts
- jest.setup.ts
- package-lock.json
- package.json
- src/__tests__/general.test.ts
- src/__tests__/gtfsflex.test.ts
- src/__tests__/gtfspathways.test.ts
- src/__tests__/osw.test.ts
- src/seeder.ts
- src/utils.ts
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/997 
Test coverage for spatial join api
> spatial join test coverage

- .github/workflows/run_tests.yml
- .gitignore
- api.input.json
- src/__tests__/osw.test.ts
- Fixed [1298](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1298/)
- Fixed [1175](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1175/)
> Fixed following issues -

- api.input.json
- assets/payloads/gtfs-flex/metadata.json
- assets/payloads/gtfs-pathways/metadata.json
- assets/payloads/osw/metadata.json
- package.json
- src/__tests__/general.test.ts
- src/__tests__/gtfsflex.test.ts
- src/__tests__/osw.test.ts
- src/models/types.ts
- src/seeder.ts
- src/utils.ts
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1720
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1722
- Added unit test cases for Ticket 1720
- Added unit test cases for Ticket 1722
> [1720, 1722] Added Test Cases

- .github/workflows/run_tests.yml
- Fixed Pipeline
- Fixed output folder format
- Refactor code to run smoothly
> Fix the pipeline

- api.input.json
- package-lock.json
- src/__tests__/general.test.ts
- src/models/types.ts
- src/seeder.ts
- src/utils.ts
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1609
- New test cases added to verify restricted access to pre-release datasets 
- For Default user , When request made with Pre-Release filter, should return empty list
- For Default user , When request made with Pre-Release dataset id filter which user does not have access, should return empty list
- For POC user , When request made with Pre-Release dataset id filter which user group owns, should return dataset list with details
- Run api tester successfully in workflow
> 1609 changes

- .github/workflows/run_tests.yml
- Fixed timestamp issue in pipeline
> Fixed timestamp issue
